### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-dollar#179] opened 2020-09-15 19:06 UTC
- [ ] Fix coverage running.
- [x] Increase test coverage.
- [ ] Add solidity coverage reporting to CI pipeline.  

The pipeline integration might need to wait until after release or a subscription service for private repos.  Something like coveralls might work.

**Comment by franckc** [comment] 2021-01-19 19:34
Closing as a dupe of #460

**Closed by franckc** 2021-01-19 19:34 UTC
Labels: P3, contracts
