### ISSUE TITLE
Large mint causes revert on fork

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#555] opened 2021-02-10 22:42 UTC
To reproduce:
Terminal A
```
export BLOCK_NUMBER=...
export PROVIDER_URL="https://eth-mainnet.alchemyapi.io/v2/..."
yarn run node:fork
```

Terminal B
```
FORK=true npx hardhat fund --index 4 --num 1 --amount 1000000 --network localhost
FORK=true npx hardhat mint --index 4 --num 1 --amount 50000 --network localhost

Minting 50000 OUSD for account 4 at address 0x1974f84881Af4204a21f18c43D7c4d9Dee331Bb5
An unexpected error occurred:

ProviderError: Transaction reverted without a reason
    at HttpProvider.request (/Users/franck/src/origin-dollar/contracts/node_modules/hardhat/src/internal/core/providers/http.ts:45:19)
    at GanacheGasMultiplierProvider.request (/Users/franck/src/origin-dollar/contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:170:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

A smaller mint (ex 1k) succeeds, so this is likely a failure in `allocate()`.

Possibly related to <https://github.com/trufflesuite/ganache-core/issues/571>

**Comment by tomlinton** [comment] 2021-03-05 01:10
Yea I think this is likely Compound. Would be interesting to try it with that strategy removed.

**Comment by sparrowDom** [comment] 2021-09-27 11:05
Fixed via: https://github.com/OriginProtocol/origin-dollar/pull/759

**Comment by crypto-ticky** [comment] 2022-08-17 12:53
I think I figured out the issue

**Comment by crypto-ticky** [comment] 2022-08-17 12:56
In VaultCore.mint function, IOracle(priceProvider).price function is called.
![image](https://user-images.githubusercontent.com/68897116/185136676-6477f396-6a96-4c5b-bb26-4282983e49e0.png)
and the priceProvider address is [https://etherscan.io/address/0x277e80f3E14E7fB3fc40A9d6184088e0241034bD#readProxyContract](url)

**Comment by DanielVF** [comment] 2022-08-17 17:44
Works in brownie: 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/837/185206949-752435e8-de7e-4a4a-a3b3-a7d4a124c4de.png">

**Comment by crypto-ticky** [comment] 2022-08-17 19:00
that worked with 24999
![image](https://user-images.githubusercontent.com/68897116/185220961-fa30194f-7e05-4291-ae64-90f3fa4d1051.png)
but when the amount is 25000, that didn't work 
![image](https://user-images.githubusercontent.com/68897116/185221278-cef32c09-be97-4fa3-b3dd-2069c1bcacb8.png)

I don't think that is hardhat issue

**Comment by crypto-ticky** [comment] 2022-08-17 19:10
Okay, now that works very well
![image](https://user-images.githubusercontent.com/68897116/185223037-aa6bf045-1078-4e75-9f57-26a62c87c574.png)

**Comment by DanielVF** [comment] 2022-08-17 19:11
So it works for 100,000, but not for 25,000?

**Comment by crypto-ticky** [comment] 2022-08-17 19:16
No, that works very well for all values 
I just updated the BLOCK_NUMBER

The issue we encountered is as follows.
First of all, the Vault address was not accurate.
Next, when this ticket was created, the market situation did not provide factors that encountered large mint. It is not clear which value is the cause of the error.
However, after I changed BLCOK_NUMBER to the latest value, the fact that it worked correctly indicates that the current market's factors are giving me conditions to do large mints.
Or an update of other contracts might have solved this problem.

**Comment by DanielVF** [comment] 2022-08-17 19:17
What BLCOK_NUMBER were you using that caused the problems?

**Comment by crypto-ticky** [comment] 2022-08-17 19:18
PROVIDER_URL=[SET PROVIDER URL HERE]
BLOCK_NUMBER=13132379
# add a list of comma separated accounts you want funded in node running forked mode
ACCOUNTS_TO_FUND=

dev.env

**Comment by crypto-ticky** [comment] 2022-08-17 19:18
PROVIDER_URL=[SET PROVIDER URL HERE]
BLOCK_NUMBER=13132379
ACCOUNTS_TO_FUND=

**Comment by crypto-ticky** [comment] 2022-08-17 19:19
BLOCK_NUMBER=15360100

That works

**Comment by DanielVF** [comment] 2022-08-17 19:19
Cool. Do you want do submit a PR on the address fix?

**Comment by crypto-ticky** [comment] 2022-08-17 19:19
yes, I am trying to do it now

**Comment by sparrowDom** [comment] 2022-08-17 21:04
@micahalcorn mind adding @crypto-ticky to the contributors team? ( https://github.com/orgs/OriginProtocol/teams/contributors/members )

**Closed** 2022-09-13 07:46 UTC
Labels: bug, P2, contracts
